added states, regions and super reigions
Touhou-Universalis/tohouniv_updated pull request #166
Opened 2024-05-27 08:58 UTC by That-Guy-Github1

divided gensokyo and the moon into 6 super regions, 26 regions and 469 states

2024-05-27 16:24 UTC, Hecatia-Lapislazuli requested changes
Seems mostly good, only thing i'd ask to be changed is area names with apostrophes in them - it might work? but is best to avoid non-standard characters (i.e. only use A-Z, a-z, -, _, which is the Regex [0-9a-zA-Z\\-\\_])

Also, localization is missing.

2024-05-27 19:55 UTC, ComradeFlan reviewed
All the new areas, regions and superregions are missing localizations. This gets my approval once they are added here too

2024-05-28 05:41 UTC, That-Guy-Github1 commented
@Hecatia-Lapislazuli localization added and apostrophes removed

2024-05-28 10:32 UTC, Hecatia-Lapislazuli requested changes
Hmm, missed it in the first review, but removing regions will break events and decisions... I suppose is somewhat fine, given that a lotta events and decisions (and missions) are broken anyways.

Also some unstandardized region naming stuff, have added mentioned them now.

I'll take a further look later today with how to handle it. May just comment out instances of it currently.

Would also like to see further localization, but not expecting that of you. Can be handled later on.

Regardless of that though...
All that's needed now is just the issues i left comments on with capitalization and missing postfixes... oh and also indentation. After that's handled should be ready to be merged in.

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> +  upper_hell: "Lower Hell"
There is an extra space on this line

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> +Youkai_Hotspring_adj: "Youkai Hotspring"
These are all missing a space on the first line

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> +  former_hell: "former_hell"
One too many spaces

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> +  former_hell: "former_hell"
should end in `_superregion` and be uncapitalized

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> + kappa_delta: "West Foot of the Mountains"
Should end with `_region`

2024-05-28 10:32 UTC, Hecatia-Lapislazuli commented on localisation/touhou_map_l_english.yml
> + misty_lake: "Misty Lake"
Should end with `_region`
Also shouldn't have capitalization for the entry (i.e. should be `great_border_region`, similarly with `Animal_realm_reigion` should be `animal_realm_reigion`)

2024-05-28 21:55 UTC, That-Guy-Github1 commented
formatting and capitalization issues fixed for localization, area, regions and superregions

2024-05-29 22:11 UTC, Hecatia-Lapislazuli approved these changes

2024-05-29 22:14 UTC, Hecatia-Lapislazuli commented
How renaming areas was handled will break missions even more by changing already existing areas, but eh, this change is better done now rather than later.

2024-05-29 22:20 UTC, merged