Big gensokyo
Touhou-Universalis/tohouniv_updated pull request #167
Opened 2024-05-30 09:41 UTC by That-Guy-Github1

update for Cirnia's mission tree, did some minor alterations to the map and province history to make the tree make more sense.

2024-05-30 10:24 UTC, Hecatia-Lapislazuli requested changes

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +			} }
OR block should be in separate line

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
>  				}
Deprecated OR block

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +			}
Indentation issues

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +				} }
Formatting

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +				}
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +				area = court_of_the_miko_area
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +					country_or_non_sovereign_subject_holds = ROOTt
Should be ROOT not ROOTt

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
>  			}
Deprecated OR block

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on events/flavorCIN.txt
> +				limit = {
Formatting (Indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on events/flavorCIN.txt
> +
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on events/flavorCIN.txt
> +				limit = {
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on events/flavorCIN.txt
> +			}
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +					NOT = { is_permanent_claim = ROOT }
This condition feels weird, and will behave weirdly. Can work for what provinces to highlight (if that's what you want), but here we shouldn't have it due to funky interactions with previously disqualified provinces becoming qualified again once we core them.

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +				region = fairy_region
Formatting (indentation)

2024-05-30 10:24 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
>  			}
Deprecated OR block

2024-05-30 23:03 UTC, Hecatia-Lapislazuli commented on missions/CIN_Missions.txt
> +					NOT = { is_permanent_claim = ROOT }
@That-Guy-Github1 I did address most of the formatting stuff you missed, but still would want to bring this one up regarding having `NOT = { is_permanent_claim = ROOT }` before approving

It should be removed from the trigger, but whether to remove from province highlighting is up to you. Am just not sure if this should be replaced with other triggers in its place. (such as areas which got permanent claims from prior events)

2024-05-31 09:34 UTC, Hecatia-Lapislazuli commented
Am still just waiting on this
https://github.com/Touhou-Universalis/tohouniv_updated/pull/167#discussion_r1621504556

> I did address most of the formatting stuff you missed, but still would want to bring this one up regarding having `NOT = { is_permanent_claim = ROOT }` before approving
> 
> It should be removed from the trigger, but whether to remove from province highlighting is up to you. Am just not sure if this should be replaced with other triggers in its place. (such as areas which got permanent claims from prior events)

2024-05-31 21:30 UTC, That-Guy-Github1 commented
> Am still just waiting on this [#167 (comment)](https://github.com/Touhou-Universalis/tohouniv_updated/pull/167#discussion_r1621504556)
> 
> > I did address most of the formatting stuff you missed, but still would want to bring this one up regarding having `NOT = { is_permanent_claim = ROOT }` before approving
> > It should be removed from the trigger, but whether to remove from province highlighting is up to you. Am just not sure if this should be replaced with other triggers in its place. (such as areas which got permanent claims from prior events)

oops sorry didn't see that fixed now

2024-05-31 23:45 UTC, Hecatia-Lapislazuli approved these changes

2024-05-31 23:45 UTC, merged